//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBMCAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppointmentRequest
    {
        public int AppointmentRequestID { get; set; }
        public string AppointmentRequestToken { get; set; }
        public int PatientID { get; set; }
        public int PhysicianID { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateRequested { get; set; }
        public System.DateTime DateScheduled { get; set; }
        public int TimeScheduled { get; set; }
        public string Note { get; set; }
        public int status { get; set; }
    
        public virtual Patient Patient { get; set; }
        public virtual Physician Physician { get; set; }
    }
}
