//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBMCAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class chemist
    {
        public int chemistId { get; set; }
        public string chemistName { get; set; }
        public string chemistPhone { get; set; }
        public string chemistEmail { get; set; }
        public string chemistAddress { get; set; }
        public System.DateTime ChemistDateOfBirth { get; set; }
    }
}
