//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBMCAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chemist
    {
        public int ChemistID { get; set; }
        public string ChemistName { get; set; }
        public string ChemistAddress { get; set; }
        public string ChemistPhone { get; set; }
        public string ChemistEmail { get; set; }
        public string ChemistSummary { get; set; }
    }
}
