//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBMCAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Drug
    {
        public int DrugID { get; set; }
        public string DrugTitle { get; set; }
        public string DrugDescription { get; set; }
        public System.DateTime DrugExpiry { get; set; }
        public string DrugDosage { get; set; }
    }
}
