//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBMCAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DrugRequest
    {
        public int DrugRequestId { get; set; }
        public int RequestPhysicianId { get; set; }
        public string RequestDescription { get; set; }
        public System.DateTime RequestedDate { get; set; }
    }
}
