//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBMCAS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Patient
    {
        public int PatientID { get; set; }
        [Required]
        [Display(Name = "Date of Birth")]
        public System.DateTime PatientDOB { get; set; }
        [Required]
        [Display(Name = "Name")]
        public string PatientName { get; set; }
        [Required]
        [Display(Name = "Permanent Address")]
        public string PatientAddress { get; set; }
        [Required]
        [Display(Name = "Mobile Number")]
        public string PatientPhone { get; set; }
        [Required]
        [Display(Name = "Email")]
        public string PatientEmail { get; set; }
        [Required]
        [Display(Name = "Gender")]
        public string PatientGender { get; set; }
        [Required]
        [Display(Name = "Medical Issue/History")]
        public string PatientSummary { get; set; }
    }
}
