//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBMCAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientRegistrationQueue
    {
        public int ID { get; set; }
        public string RegistrationTokenID { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime PatientDOB { get; set; }
        public string PatientFirstName { get; set; }
        public string PatientLastName { get; set; }
        public string PatientAddress { get; set; }
        public string PatientPhone { get; set; }
        public string PatientEmail { get; set; }
        public string PatientGender { get; set; }
        public string PatientMedicalHistory { get; set; }
        public string PatientAadhaarNumber { get; set; }
    }
}
