//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBMCAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Physician
    {
        public int PhysicianID { get; set; }
        public string PhysicianName { get; set; }
        public string PhysicianAddress { get; set; }
        public string PhysicianPhone { get; set; }
        public string PhysicianEmail { get; set; }
        public string PhysicianSpecialization { get; set; }
        public string PhysicianSummary { get; set; }
    }
}
