//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBMCAS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Physician
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Physician()
        {
            this.Appointments = new HashSet<Appointment>();
            this.AppointmentRequests = new HashSet<AppointmentRequest>();
            this.DrugRequests = new HashSet<DrugRequest>();
        }
    
        public int PhysicianID { get; set; }
        public string PhysicianName { get; set; }
        public string PhysicianAddress { get; set; }

        [MaxLength(10)]
        [MinLength(10)]
        public string PhysicianPhone { get; set; }

        [EmailValidation]
        public string PhysicianEmail { get; set; }
        public string PhysicianSpecialization { get; set; }
        public string PhysicianSummary { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Appointment> Appointments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppointmentRequest> AppointmentRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DrugRequest> DrugRequests { get; set; }
    }
}
