//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBMCAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrderProductLine
    {
        public int PurchaseOrderProductLineId { get; set; }
        public int PurchaseOrderId { get; set; }
        public int DrugId { get; set; }
        public int Qty { get; set; }
        public string ShortNote { get; set; }
    
        public virtual Drug Drug { get; set; }
        public virtual PurchaseOrderHeader PurchaseOrderHeader { get; set; }
    }
}
